version: 2

before:
  hooks:
    - go mod tidy
    - sh -c 'ls .release-extra/*.vsix >/dev/null'

gomod:
  proxy: false
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  mod: mod

builds:
  - id: thriftfmt
    main: ./cmd/thriftfmt
    binary: thriftfmt
    flags: &go_build_flags
      - -buildvcs=false
    env: &go_pure_env
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: thriftls
    main: ./cmd/thriftls
    binary: thriftls
    flags: *go_build_flags
    env: *go_pure_env
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: thriftlint
    main: ./cmd/thriftlint
    binary: thriftlint
    flags: *go_build_flags
    env: *go_pure_env
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: thriftfmt
    ids:
      - thriftfmt
    name_template: >-
      {{ .Binary }}_
      {{- .Version }}-
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
  - id: thriftls
    ids:
      - thriftls
    name_template: >-
      {{ .Binary }}_
      {{- .Version }}-
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
  - id: thriftlint
    ids:
      - thriftlint
    name_template: >-
      {{ .Binary }}_
      {{- .Version }}-
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
  extra_files: &release_extra_files
    - glob: .release-extra/*.vsix
    - glob: docs/release.md
      name_template: UNSIGNED-BETA-RELEASE-POLICY.md

release:
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  extra_files: *release_extra_files

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - '.*\[docs?\]$'
      - "^test:"
      - '.*\[tests?\]$'
      - "^lint:"
      - '.*\[lint\]$'
      - "^chore"
      - '.*\[chore\]$'
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

# Notes:
# - Release workflow runs GoReleaser on a standard Ubuntu runner and produces pure-Go (`CGO_ENABLED=0`) artifacts.
# - `thriftls` managed-install manifest / VS Code release metadata are generated by repo scripts after GoReleaser creates archives/checksums.
# - Windows arm64 publication remains best-effort until runtime validation is fully automated.
