version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/kpumuk/thrift-weaver
  mod: mod

builds:
  - id: thriftfmt
    main: ./cmd/thriftfmt
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: thriftls
    main: ./cmd/thriftls
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - '.*\[docs?\]$'
      - "^test:"
      - '.*\[tests?\]$'
      - "^lint:"
      - '.*\[lint\]$'
      - "^chore"
      - '.*\[chore\]$'
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

# Notes:
# - This is an M0 skeleton and intentionally does not finalize cgo/cross-compile strategy.
# - Tree-sitter/cgo release matrix constraints will be refined in later milestones.
# - `thriftls` managed-install manifest generation is handled by release workflow/scripts (placeholder in M0).
