pre-push:
  jobs:
    - name: packages audit
      tags:
        - security
      run: mise exec golang -- go tool golang.org/x/vuln/cmd/govulncheck ./...

pre-commit:
  fail_on_changes: "always"
  jobs:
    - name: generate tree-sitter parser
      glob:
        - "grammar/tree-sitter-thrift/grammar.js"
        - "grammar/tree-sitter-thrift/tree-sitter.json"
        - "scripts/generate-tree-sitter.sh"
        - "mise.toml"
      run: mise exec tree-sitter -- scripts/generate-tree-sitter.sh

    - name: lint
      glob:
        - ".golangci.yml"
        - "*.go"
        - "go.mod"
        - "go.sum"
        - "mise.toml"
      run: mise run lint --fix

    - name: test
      glob:
        - "*.go"
        - "go.mod"
        - "go.sum"
      run: mise run test

    - name: vscode extension ci
      glob:
        - "editors/vscode/**"
        - "mise.toml"
      run: mise run vscode-ci
